version: '3.9'

services:
  csharpapp:
    container_name: node
    image: node
    build: .
    ports:
      - "8000:8000"
    environment:
      ConnectionStrings__DefaultConnection: "Host=dbM;Database=postgres;Username=postgres;Password=postgres"
    depends_on:
      - dbM
  
  dbM:
    container_name: dbM
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seeds:/docker-entrypoint-initdb.d

volumes:
  pgdata: {}